### ISSUE TITLE
Include DOI/ISSN reference on Bibliography

### ISSUE THREAD

**Issue by vvalente** [yazhao/PSU_Thesis#2]
Hello. I've been using this template for a while now and realized that the DOI/ISSN information needs to be added to the references when compiling, even though the .bib file has them. For some areas, that information is required. Is there an easy way to include this? Is this something I would need to enable? I've tried changing some code on the .bst file but without success. I appreciate any help.

**Comment by yazhao** [comment]
Sorry for the late reply, this is generally not checked very often. I believe it would be possible to add DOI/ISSN information by modifying the .bst file similar to this link: https://latex.org/forum/viewtopic.php?t=10046

Specifically, I believe you can try:
1. In the ENTRY section, add doi/issn as an item
2. Add some item like: doi empty$ to the specific FUNCTION that you want

Note that you'd have to do this for each type of citation that has a doi that you want, so if you have an article that has a doi you'd have to add it to the FUNCTION {article} section, and then if you have doi's for books you'd have to add them to FUNCTION {book}
